from datetime import datetime
from typing import Dict, List

TOOL_NAME = "iomux_gen"
TOOL_VERSION = "1.0.0"
_GEN_HEADER: List[str] = []


def set_gen_header(meta: Dict[str, str]):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"// Auto-generated by {TOOL_NAME} v{TOOL_VERSION}",
        f"// Generated at {ts}",
    ]
    for k, v in meta.items():
        lines.append(f"// {k}: {v}")
    global _GEN_HEADER
    _GEN_HEADER = lines


def banner() -> List[str]:
    return _GEN_HEADER[:] if _GEN_HEADER else [f"// Auto-generated by {TOOL_NAME} v{TOOL_VERSION}"]

